### ISSUE TITLE
Capacitor 6.x compatibility

### ISSUE THREAD

**Issue by whiteua** [kduma-autoid/capacitor-bluetooth-printer#2]
Hello. 
I tried to install the plugin on @capacitor/core@6.0.0 and got the following error from NPM:

npm install @kduma-autoid/capacitor-bluetooth-printer
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: quasar-project@0.0.1
npm error Found: @capacitor/core@6.0.0
npm error node_modules/@capacitor/core
npm error   @capacitor/core@"6.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @capacitor/core@"^5.0.0" from @kduma-autoid/capacitor-bluetooth-printer@0.1.0
npm error node_modules/@kduma-autoid/capacitor-bluetooth-printer
npm error   @kduma-autoid/capacitor-bluetooth-printer@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

Regards, Alex.

**Comment by kduma** [comment]
At this moment my plugins are not yet updated for capacitor 6.x. I will be updating them while upgrading my apps, which depends on them. But feel free to make a pull request if you need it quicker. :)

**Comment by logistiko-israel** [comment]
Hi! I've created the following draft pr to support Capacitor 6.x. https://github.com/kduma-autoid/capacitor-bluetooth-printer/pull/3

I removed a dependency that was used in the example app and the only thing missing is assigning a version number.

Have a great weekend!

**Comment by kduma** [comment]
Thank You. The PR is marked as a "draft". Is it ready to review? If yes, I will check it and publish a new version as soon as I have time.

**Comment by kumibrr** [comment]
> Thank You. The PR is marked as a "draft". Is it ready to review? If yes, I will check it and publish a new version as soon as I have time.

Thank **you**

And yeah, it is marked as a draft until I change the new version number. Should it be 0.2.0?

**Comment by logistiko-israel** [comment]
> Thank You. The PR is marked as a "draft". Is it ready to review? If yes, I will check it and publish a new version as soon as I have time.

Thank **you** for making this plugin.

And yeah, it is marked as a draft until I change the new version number. Should it be 0.2.0?

**Comment by kduma** [comment]
Actually, you don't need to update the version number as version bumping is part of the [release scripts](https://github.com/kduma-autoid/capacitor-bluetooth-printer/blob/main/.scripts/bump_version.sh).

**Comment by kduma** [comment]
PR merged and released! Thanks for your contribution 😉
